Source/Web/OnlineStore.Web/Areas/Admin/ViewModels/EditUserViewModel.cs
namespace OnlineStore.Web.Areas.Admin.ViewModels
{
    using OnlineStore.Models;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public class EditUserViewModel
    {
        public ApplicationUser User { get; set; }

        public string Password { get; set; }

        [DisplayName("Confirm Password")]
        [Compare("Password", ErrorMessage = "Password does  not mathch.")]
        public string ConfirmPassword { get; set; }

        public IList<Role> Roles { get; set; }
    }
}

Source/Web/OnlineStore.Web/ViewModels/Category/ListViewModel.cs
namespace OnlineStore.Web.ViewModels.Category
{
    using Infrastructure.Mapping;
    using System.Collections.Generic;
    using AutoMapper;

    public class ListViewModel: IMapFrom<OnlineStore.Models.Category>, IHaveCustomMappings
    {
        public ListViewModel()
        {
            this.CategoryItems = new HashSet<CategoryItem>();
        }
        
        public int Id { get; set; }

        public string Name { get; set; }

        public ICollection<CategoryItem> CategoryItems { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<OnlineStore.Models.Category, ListViewModel>()
            .ForMember(x => x.CategoryItems, opt => opt.MapFrom(x => x.Products));
        }
    }
}

Source/Web/OnlineStore.Web/Areas/Admin/Controllers/EditUserController.cs
namespace OnlineStore.Web.Areas.Admin.Controllers
{
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using OnlineStore.Models;
    using Web.Controllers;
    using Data.UnitOfWork;
    using Microsoft.AspNet.Identity;
    using ViewModels;
    using Microsoft.AspNet.Identity.Owin;
    using System.Data.Entity.Infrastructure;
    using Microsoft.AspNet.Identity.EntityFramework;

    [Authorize(Roles = "Admin")]
    public class EditUserController : BaseController
    {
        public EditUserController(IStoreDb data)
            : base(data)
        {
        }

        // GET: User
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET: User/List
        public ActionResult List()
        {

            var users = this.Data.Users.All().ToList();

            var admins = GetAdminUserNames(users, Data);
            ViewBag.Admins = admins;

            return View(users);

        }

        private HashSet<string> GetAdminUserNames(List<ApplicationUser> users, IStoreDb data)
        {
            // Create user manager
            var userManager = Request
                .GetOwinContext()
                .GetUserManager<ApplicationUserManager>();

            var admins = new HashSet<string>();

            foreach (var user in users)
            {
                if (userManager.IsInRole(user.Id, "Admin"))
                {
                    admins.Add(user.UserName);
                }
            }

            return admins;
        }


        // GET: User/Edit
        public ActionResult Edit(string id)
        {
            //validate id
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Get user from DB
            var user = Data.Users.All().FirstOrDefault(x=>x.Id == id);

            // Check if user exists
            if (user == null)
            {
                return HttpNotFound();
            }


            // Create a view model
            var viewModel = new EditUserViewModel();
            viewModel.User = user;
            viewModel.Roles = GetUserRoles(user, Data);

            // Pass the model to the view
            return View(viewModel);
        }

        // POST: User/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, EditUserViewModel viewModel)
        {
            // Check if model is valid
            if (ModelState.IsValid)
            {

                // Get user from Data
                var user = Data.Users.All().FirstOrDefault(x => x.Id == id);

                // Check if user exists
                if (user == null)
                {
                    return HttpNotFound();
                }

                // If password field is not empty, change password
                if (!string.IsNullOrEmpty(viewModel.Password))
                {
                    var hasher = new PasswordHasher();
                    var passwordHash = hasher.HashPassword(viewModel.Password);
                    user.PasswordHash = passwordHash;
                }

                // Set user properties
                user.Email = viewModel.User.Email;
                user.UserName = user.Email;
                user.FirstName = viewModel.User.FirstName;
                user.LastName = viewModel.User.LastName;
                this.SetUserRoles(viewModel, user, Data);

                // Save changes
                Data.SaveChanges();
                return RedirectToAction("List");
            }

            return View(viewModel);
        }

        // GET: User/Delete
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // get user from Data
            var user = Data.Users.All().FirstOrDefault(x => x.Id == id);

            // Check if user exists
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);

        }

        // POST: User/Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Get user from Data
            var user = Data.Users.All().FirstOrDefault(x => x.Id == id);

            // Delete user and save changes
            Data.Users.Delete(user);
            Data.SaveChanges();

            return RedirectToAction("List");

        }

        private void SetUserRoles(EditUserViewModel viewModel, ApplicationUser user, IStoreDb Data)
        {
            var userManager = HttpContext
                .GetOwinContext()
                .GetUserManager<ApplicationUserManager>();

            foreach (var role in viewModel.Roles)
            {
                if (role.IsSelected && !userManager.IsInRole(user.Id, role.Name))
                {
                    userManager.AddToRole(user.Id, role.Name);
                }
                else if (!role.IsSelected && userManager.IsInRole(user.Id, role.Name))
                {
                    userManager.RemoveFromRole(user.Id, role.Name);
                }
            }
        }

        private IList<Role> GetUserRoles(ApplicationUser user, IStoreDb db)
        {
            // Create user manager
            var userManager = Request
                .GetOwinContext()
                .GetUserManager<ApplicationUserManager>();

            // Get all  application roles
            var roles = db.IdentityRoles.All()
                .Select(r => r.Name)
                .OrderBy(r => r)
                .ToList();

            // For each application role, check if the user has it
            var userRoles = new List<Role>();

            foreach (var roleName in roles)
            {
                var role = new Role { Name = roleName };

                if (userManager.IsInRole(user.Id, roleName))
                {
                    role.IsSelected = true;
                }

                userRoles.Add(role);
            }

            // Return a list with all roles
            return userRoles;
        }
    }
}

Source/Web/OnlineStore.Web/Areas/Admin/Controllers/EditUsersController.cs
namespace OnlineStore.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using OnlineStore.Data;
    using OnlineStore.Models;
    using OnlineStore.Web.Controllers;
    using OnlineStore.Data.UnitOfWork;

    public class EditUsersController : BaseController
    {
        public EditUsersController(IStoreDb data)
            :base(data)
        {
        }

        // GET: Admin/EditUsers
        public ActionResult Index()
        {
            return View(Data.Users.All().ToList());
        }

        // GET: Admin/EditUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = Data.Users.GetById(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: Admin/EditUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/EditUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                Data.Users.Add(applicationUser);
                Data.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        // GET: Admin/EditUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = Data.Users.GetById(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Admin/EditUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                Data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: Admin/EditUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = Data.Users.GetById(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Admin/EditUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            ApplicationUser applicationUser = Data.Users.GetById(id);
            Data.Users.Delete(applicationUser);
            Data.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Source/Web/OnlineStore.Web/Areas/Admin/Views/EditUser/Delete.cshtml
@model OnlineStore.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationUser</h4>
    <hr />
	@using (Html.BeginForm("Delete", "EditUser", FormMethod.Post, new { @class = "form-horizontal" }))
	{
		@Html.AntiForgeryToken()
		<div class="form-group">
			@Html.LabelFor(m => m.UserName, new { @class = "control-label col-sm-4" })
			<div class="col-sm-4">
				@Html.TextBoxFor(m => m.UserName, new { @class = "form-control col-sm-4", @readonly = "readonly" })
			</div>
		</div>

			<div class="form-group">
				@Html.LabelFor(m => m.FirstName, new { @class = "control-label col-sm-4" })
				<div class="col-sm-4">
					@Html.TextBoxFor(m => m.LastName, new { @class = "form-control col-sm-4", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(m => m.FirstName, new { @class = "control-label col-sm-4" })
				<div class="col-sm-4">
					@Html.TextBoxFor(m => m.LastName, new { @class = "form-control col-sm-4", @readonly = "readonly" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-4">
					@Html.ActionLink("Cancel", "List", "User", null, new { @class = "btn btn-default" })
					<input type="submit" value="Delete" class="btn btn-danger" />
				</div>
			</div>
	}
</div>

Source/Web/OnlineStore.Web/Areas/Admin/Views/EditUser/Edit.cshtml
@model OnlineStore.Web.Areas.Admin.ViewModels.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
    <hr />
	@Html.ValidationSummary()
	@Html.AntiForgeryToken()

	@using (Html.BeginForm("Edit", "EditUser", FormMethod.Post, new { @class = "form-horizontal" }))
	{
		@Html.AntiForgeryToken()
		<div class="form-group">
			@Html.LabelFor(m => m.User.Email, new { @class = "control-label col-sm-4" })
			<div class="col-sm-4">
				@Html.TextBoxFor(m => m.User.Email, new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.User.FirstName, new { @class = "control-label col-sm-4" })
			<div class="col-sm-4">
				@Html.TextBoxFor(m => m.User.FirstName, new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.User.LastName, new { @class = "control-label col-sm-4" })
			<div class="col-sm-4">
				@Html.TextBoxFor(m => m.User.LastName, new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.Password, new { @class = "control-label col-sm-4" })
			<div class="col-sm-4">
				@Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label col-sm-4" })
			<div class="col-sm-4">
				@Html.TextBoxFor(m => m.ConfirmPassword, new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			@for (int i = 0; i < Model.Roles.Count; i++)
			{
				<div class="col-sm-offset-4 col-sm-4">
					@Html.HiddenFor(m => m.Roles[i].Name)
					@Html.CheckBoxFor(m => m.Roles[i].IsSelected)
					@Model.Roles[i].Name
				</div>
			}
		</div>

		<div class="form-group">
			<div class="col-sm-4 col-sm-offset-4">
				<input type="submit" value="Edit" class="btn btn-success" />
			</div>
		</div>
	}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Source/Web/OnlineStore.Web/Areas/Admin/Views/EditUser/List.cshtml
@model IEnumerable<OnlineStore.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var user in Model)
		{
			if (ViewBag.Admins.Contains(user.UserName))
			{
				@:<tr class="info">
            }
			else
			{
				@:<tr>
            }

			<td>@user.Id</td>
					<td>@user.Email</td>
					<td>
						@Html.ActionLink("Edit", "Edit", "EditUser", new { @id = user.Id }, null)
						@Html.ActionLink("Delete", "Delete", "EditUser", new { @id = user.Id }, null)
					</td>
		}
</tbody>
</table>